# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # node/npm code dependencies
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50

  - package-ecosystem: "elm" # Elm
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50

  - package-ecosystem: "elm-review" # Elm-review elm dependencies
    directory: "/review" # Location of package manifests
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 50
